version: "3.7"

services:
  api_v1:
    build:
      context: ./test
      dockerfile: Dockerfile
      args:
        GIT_BRANCH_NAME: ${GIT_BRANCH_NAME}
    container_name: autoxtrabackup_apiv1_test
    volumes:
    - ./test/entrypoint.sh:/entrypoint.sh
    - /dev/log:/dev/log
    ports:
    - 8000:8000
    networks:
      - wide_network
      - internal_network

networks:
  internal_network:
    name: fd_internal_net
    internal: true
  wide_network:
    name: fd_wide_net
    driver: bridge


