version: "3.7"

services:
  autoxtrabackup:
    build:
      context: tests
      dockerfile: Dockerfile
      args:
        GIT_BRANCH_NAME: ${GIT_BRANCH_NAME}
    container_name: autoxtrabackup_apiv1_test
    volumes:
    - /dev/log:/dev/log
    - .:/opt/MySQL-AutoXtraBackup
    ports:
    - "8080:8080"
    network_mode: host


